import type { Parcel } from '../types'

export const parcels: Parcel[] = [
  {
    id: 'LA-2024-001',
    projectName: 'Eastern Expressway Corridor',
    district: 'Nagpur',
    state: 'Maharashtra',
    areaHectares: 142.5,
    affectedFamilies: 320,
    landType: 'Agricultural',
    stage: 'Compensation',
    daysInCurrentStage: 168,
    pendingLitigations: 4,
    compensationDisputes: 6,
    ownerConsentPct: 58,
    documentationCompletePct: 72,
    budgetApproved: false,
    monsoonSeason: true,
    publicObjections: 21,
    startDate: '2024-01-15',
    targetHandoverDate: '2025-06-30',
  },
  {
    id: 'LA-2024-002',
    projectName: 'Riverfront Smart City Phase 2',
    district: 'Ahmedabad',
    state: 'Gujarat',
    areaHectares: 88.0,
    affectedFamilies: 145,
    landType: 'Residential',
    stage: 'Valuation',
    daysInCurrentStage: 41,
    pendingLitigations: 1,
    compensationDisputes: 2,
    ownerConsentPct: 84,
    documentationCompletePct: 91,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 5,
    startDate: '2024-03-01',
    targetHandoverDate: '2025-04-15',
  },
  {
    id: 'LA-2024-003',
    projectName: 'National Highway 44 Widening',
    district: 'Kurnool',
    state: 'Andhra Pradesh',
    areaHectares: 210.3,
    affectedFamilies: 410,
    landType: 'Agricultural',
    stage: 'Survey',
    daysInCurrentStage: 134,
    pendingLitigations: 3,
    compensationDisputes: 4,
    ownerConsentPct: 47,
    documentationCompletePct: 55,
    budgetApproved: true,
    monsoonSeason: true,
    publicObjections: 28,
    startDate: '2024-02-10',
    targetHandoverDate: '2025-09-01',
  },
  {
    id: 'LA-2024-004',
    projectName: 'Metro Rail Depot Extension',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    areaHectares: 24.7,
    affectedFamilies: 62,
    landType: 'Commercial',
    stage: 'Possession',
    daysInCurrentStage: 22,
    pendingLitigations: 0,
    compensationDisputes: 0,
    ownerConsentPct: 96,
    documentationCompletePct: 98,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 1,
    startDate: '2023-11-05',
    targetHandoverDate: '2025-01-20',
  },
  {
    id: 'LA-2024-005',
    projectName: 'Coastal Thermal Power Plant',
    district: 'Cuttack',
    state: 'Odisha',
    areaHectares: 305.0,
    affectedFamilies: 520,
    landType: 'Forest',
    stage: 'Notification',
    daysInCurrentStage: 88,
    pendingLitigations: 5,
    compensationDisputes: 7,
    ownerConsentPct: 33,
    documentationCompletePct: 40,
    budgetApproved: false,
    monsoonSeason: true,
    publicObjections: 44,
    startDate: '2024-04-20',
    targetHandoverDate: '2026-03-31',
  },
  {
    id: 'LA-2024-006',
    projectName: 'Industrial Logistics Park',
    district: 'Sonipat',
    state: 'Haryana',
    areaHectares: 66.2,
    affectedFamilies: 90,
    landType: 'Barren',
    stage: 'Valuation',
    daysInCurrentStage: 30,
    pendingLitigations: 0,
    compensationDisputes: 1,
    ownerConsentPct: 89,
    documentationCompletePct: 88,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 3,
    startDate: '2024-05-01',
    targetHandoverDate: '2025-05-30',
  },
  {
    id: 'LA-2024-007',
    projectName: 'Irrigation Canal Network',
    district: 'Jhansi',
    state: 'Uttar Pradesh',
    areaHectares: 178.9,
    affectedFamilies: 275,
    landType: 'Agricultural',
    stage: 'Compensation',
    daysInCurrentStage: 96,
    pendingLitigations: 2,
    compensationDisputes: 3,
    ownerConsentPct: 71,
    documentationCompletePct: 80,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 12,
    startDate: '2024-01-25',
    targetHandoverDate: '2025-08-10',
  },
  {
    id: 'LA-2024-008',
    projectName: 'Airport Perimeter Acquisition',
    district: 'Jewar',
    state: 'Uttar Pradesh',
    areaHectares: 412.0,
    affectedFamilies: 680,
    landType: 'Agricultural',
    stage: 'Survey',
    daysInCurrentStage: 112,
    pendingLitigations: 6,
    compensationDisputes: 9,
    ownerConsentPct: 52,
    documentationCompletePct: 63,
    budgetApproved: false,
    monsoonSeason: false,
    publicObjections: 37,
    startDate: '2023-12-12',
    targetHandoverDate: '2025-11-30',
  },
  {
    id: 'LA-2024-009',
    projectName: 'Ring Road Junction Upgrade',
    district: 'Indore',
    state: 'Madhya Pradesh',
    areaHectares: 19.4,
    affectedFamilies: 34,
    landType: 'Commercial',
    stage: 'Compensation',
    daysInCurrentStage: 44,
    pendingLitigations: 1,
    compensationDisputes: 1,
    ownerConsentPct: 82,
    documentationCompletePct: 90,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 4,
    startDate: '2024-06-01',
    targetHandoverDate: '2025-03-15',
  },
  {
    id: 'LA-2024-010',
    projectName: 'Solar Park Land Bank',
    district: 'Jaisalmer',
    state: 'Rajasthan',
    areaHectares: 540.0,
    affectedFamilies: 48,
    landType: 'Barren',
    stage: 'Notification',
    daysInCurrentStage: 35,
    pendingLitigations: 0,
    compensationDisputes: 0,
    ownerConsentPct: 93,
    documentationCompletePct: 85,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 2,
    startDate: '2024-07-10',
    targetHandoverDate: '2025-07-01',
  },
  {
    id: 'LA-2024-011',
    projectName: 'Riverbank Flood Defense',
    district: 'Patna',
    state: 'Bihar',
    areaHectares: 97.6,
    affectedFamilies: 210,
    landType: 'Residential',
    stage: 'Survey',
    daysInCurrentStage: 158,
    pendingLitigations: 4,
    compensationDisputes: 5,
    ownerConsentPct: 44,
    documentationCompletePct: 51,
    budgetApproved: false,
    monsoonSeason: true,
    publicObjections: 33,
    startDate: '2024-02-28',
    targetHandoverDate: '2026-01-15',
  },
  {
    id: 'LA-2024-012',
    projectName: 'Tech Corridor SEZ',
    district: 'Pune',
    state: 'Maharashtra',
    areaHectares: 133.3,
    affectedFamilies: 118,
    landType: 'Commercial',
    stage: 'Valuation',
    daysInCurrentStage: 58,
    pendingLitigations: 1,
    compensationDisputes: 2,
    ownerConsentPct: 78,
    documentationCompletePct: 83,
    budgetApproved: true,
    monsoonSeason: false,
    publicObjections: 7,
    startDate: '2024-04-05',
    targetHandoverDate: '2025-06-20',
  },
]

export function getParcel(id: string): Parcel | undefined {
  return parcels.find((p) => p.id === id)
}
